name: Test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
    - run: npm install --no-audit
    - run: npm audit --audit-level=low
    - run: npx c8 -r lcovonly -r text --check-coverage --100 npm test
    - run: node --import=@litejs/cli/test.js test/load.mjs
    - name: Browser tests
      run: |
        npx lj serve &
        google-chrome --headless --virtual-time-budget=3000 --enable-logging=stderr http://127.0.0.1:8080/test/index.html 2>&1 | sed -n '/INFO:CONSOLE/s,.*"\(.*\)".*,\1,p' | tee /tmp/browser-test.txt
        grep -q "# pass" /tmp/browser-test.txt && ! grep -q "FAIL" /tmp/browser-test.txt
    - run: npx lj lint
    - run: ./test/readme.sh
    - run: npx tsc -p test/tsconfig.json --noEmit
    - uses: coverallsapp/github-action@v2
      name: Upload to coveralls.io
      with:
        github-token: ${{ github.token }}
  Bun:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: oven-sh/setup-bun@v2
    - run: bun i
    - run: bun x lj t
  Test:
    strategy:
      matrix:
        include:
        - { node: 8,  os: ubuntu-24.04,   arch: x86 }
        - { node: 10, os: windows-2022,   arch: x86 }
        - { node: 16, os: ubuntu-latest,  arch: x64 }
        - { node: 22, os: macos-latest,   arch: arm64 }
    runs-on: ${{ matrix.os }}
    name: Node ${{matrix.node}} (${{matrix.os}} ${{matrix.arch}})
    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node }}
        architecture: ${{ matrix.arch }}
    - run: npm install --no-audit
    - run: npm test
  Analyze:
    uses: litejs/.github/.github/workflows/analyze.yml@main
  Release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [Analyze, Coverage, Test]
    uses: litejs/.github/.github/workflows/release.yml@main
    secrets: inherit

